---
- hosts: 'all'
  tasks:
  - name: 'brew init'
    lineinfile:
      path: '~/.bashrc'
      line: 'export PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"'
      create: true

  - name: 'apt: upgrade'
    apt:
      upgrade: 'dist'
      update_cache: true
    become: true

  - name: 'brew: upgrade'
    homebrew:
      state: 'latest'
      upgrade_all: true
      update_homebrew: true
